pipeline {
    agent {
        docker { 
            image 'node:20-alpine'
            label 'docker'  // Directs execution to your dedicated docker-agent
        }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
                sh 'sleep 30' // Keeps the container active so you can catch it
            }
        }
    }
}
